// Generated by Beat Phaser Track Editor. Do not edit by hand.
package com.rmichels.phasegame.audio

import com.rmichels.phasegame.R

internal data class BackingTrackTier(
    val tier: Int,
    val sampleId: AudioSampleId,
    val rawResource: Int
)

internal data class BackingTrackDefinition(
    val id: String,
    val title: String,
    val bpm: Float,
    val stepsPerBeat: Int,
    val stepCount: Int,
    val tiers: List<BackingTrackTier>
)

internal object GeneratedBackingTrackCatalog {
    val tracks = listOf(
        BackingTrackDefinition(
            id = "new_backing_track", title = "New backing track", bpm = 60.000f,
            stepsPerBeat = 4, stepCount = 12,
            tiers = listOf(
                BackingTrackTier(1, AudioSampleId(41), R.raw.backing_new_backing_track_tier_01),
                BackingTrackTier(2, AudioSampleId(42), R.raw.backing_new_backing_track_tier_02),
                BackingTrackTier(3, AudioSampleId(43), R.raw.backing_new_backing_track_tier_03),
                BackingTrackTier(4, AudioSampleId(44), R.raw.backing_new_backing_track_tier_04),
            )
        ),
    )
}
